name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: python:3.11.6-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Install required tools
      run: |
        pip install pipenv
        ls -l
      shell: /bin/sh